// Service Worker — auto-generated by PWA 打包神器
// Cache key: ai-pmp-v1
// Strategy: Stale-While-Revalidate (HTML) + Cache-First (assets)

const CACHE_NAME = 'ai-pmp-v1';
const PRECACHE_URLS = [
    "/ai-pmp/index.html",
    "/ai-pmp/sw.js",
    "/ai-pmp/manifest.json",
    "/ai-pmp/icon.svg",
    "/ai-pmp/icon-192.png",
    "/ai-pmp/icon-512.png"
];

self.addEventListener('install', event => {
  event.waitUntil(
    caches.open(CACHE_NAME).then(cache => {
      return cache.addAll(PRECACHE_URLS).catch(err => {
        console.warn('[SW] Pre-cache partial failure:', err);
      });
    }).then(() => self.skipWaiting())
  );
});

self.addEventListener('activate', event => {
  event.waitUntil(
    caches.keys().then(keys =>
      Promise.all(
        keys.filter(k => k !== CACHE_NAME)
            .map(k => caches.delete(k))
      )
    ).then(() => self.clients.claim())
  );
});

self.addEventListener('fetch', event => {
  if (event.request.method !== 'GET') return;
  const url = new URL(event.request.url);
  if (url.protocol === 'chrome-extension:') return;

  const isDocument = event.request.destination === 'document' ||
                     event.request.headers.get('accept')?.includes('text/html');

  if (isDocument) {
    event.respondWith(
      caches.open(CACHE_NAME).then(cache =>
        cache.match(event.request).then(cached => {
          const fetchPromise = fetch(event.request).then(response => {
            if (response && response.status === 200) {
              cache.put(event.request, response.clone());
            }
            return response;
          }).catch(() => null);
          return cached || fetchPromise || Promise.resolve(new Response("Offline", {status: 503}));
        })
      )
    );
  } else {
    event.respondWith(
      caches.match(event.request).then(cached => {
        if (cached) return cached;
        return fetch(event.request).then(response => {
          if (!response || response.status !== 200 || response.type === 'opaque') {
            return response;
          }
          const cloned = response.clone();
          caches.open(CACHE_NAME).then(cache => cache.put(event.request, cloned));
          return response;
        }).catch(() => {
          // offline — no asset fallback
        });
      })
    );
  }
});
